### ISSUE TITLE
mongodb

### ISSUE THREAD

**Issue by blueink38** [blueink38/beer-me#7]
- create database using mongodb

**Comment by DragoonKite** [comment]
database and server set up. Still need Seeds and Models

**Comment by DragoonKite** [comment]
User and Brewery Model added

**Comment by DragoonKite** [comment]
Queries added: me, users, brewery (single brewery by name), breweryCity, breweryType, breweryState

Mutations added: addUser, deleteUsers, addBrewery, addSavedBrewery, login
